// src/main/services/apiErrorHandler.ts

import { getTradingAssistantWindow } from '../windows/tradingAssistantWindow';

export enum ApiErrorCategory {
  INVALID_ARGUMENT = 'INVALID_ARGUMENT',
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  NOT_FOUND = 'NOT_FOUND',
  INTERNAL = 'INTERNAL',
  RESOURCE_EXHAUSTED = 'RESOURCE_EXHAUSTED',
  FAILED_PRECONDITION = 'FAILED_PRECONDITION',
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  UNIMPLEMENTED = 'UNIMPLEMENTED',
  UNAVAILABLE = 'UNAVAILABLE',
}

export interface ApiErrorResult {
  message: string;
  category: ApiErrorCategory;
  shouldRetry: boolean;
  retryDelayMs?: number;
}

const errorMessages: Record<number, { message: string; category: ApiErrorCategory }> = {
  12001: { message: 'Метод не реализован.', category: ApiErrorCategory.UNIMPLEMENTED },
  12002: { message: 'Устаревший метод недоступен.', category: ApiErrorCategory.UNAVAILABLE },
  30001: { message: 'Параметр from обязателен.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30002: { message: 'Запрошенный период не может превышать 14 дней.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30003: { message: 'from не может быть меньше текущей даты.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30004: { message: 'Параметр to обязателен.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30005: { message: 'Некорректный id_type.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30006: { message: 'Параметр id_type обязателен.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30007: { message: 'Параметр id обязателен.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30008: { message: 'Параметр figi обязателен.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30009: { message: 'Некорректный параметр from.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30010: { message: 'Некорректный параметр to.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30011: { message: 'Некорректный интервал.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30012: { message: 'to не может быть меньше from.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30013: { message: 'class_code обязателен при поиске по тикеру.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30014: { message: 'Превышен максимальный период запроса для данного интервала свечи.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30015: { message: 'Параметр quantity обязателен и должен быть больше 0.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30016: { message: 'Некорректный параметр quantity.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30017: { message: 'Параметр price обязателен.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30018: { message: 'Некорректный параметр price.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30019: { message: 'Параметр direction обязателен.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30020: { message: 'Некорректный direction.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30021: { message: 'Параметр account_id обязателен.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30022: { message: 'Некорректный account_id.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30023: { message: 'Некорректный параметр state.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30025: { message: 'Параметр order_type обязателен.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30026: { message: 'Некорректный order_type.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30027: { message: 'Параметр order_id обязателен.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30028: { message: 'order_id имеет неверный формат UUID.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30029: { message: 'Параметр idempotency_key обязателен.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30030: { message: 'Некорректный idempotency_key.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30031: { message: 'Параметр depth обязателен.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30032: { message: 'Некорректный параметр depth.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30033: { message: 'trade_clearing_account или class_code обязателен.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30034: { message: 'Недостаточно средств для совершения сделки.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30035: { message: 'Некорректный stop_price.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30036: { message: 'Параметр stop_price обязателен.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30037: { message: 'Параметр stop_order_type обязателен.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30038: { message: 'Некорректный stop_order_type.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30039: { message: 'Некорректный параметр trailing_data.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30040: { message: 'Некорректный expire_date.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30041: { message: 'Метод доступен только для фьючерсов.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30042: { message: 'Недостаточно активов для маржинальной сделки.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30043: { message: 'Параметр expiration_type обязателен.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30044: { message: 'Некорректный expiration_type.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30045: { message: 'Параметр ticker обязателен.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30047: { message: 'Валюта цены не совпадает с валютой расчётов по инструменту.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30048: { message: 'Метод доступен только для облигаций.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30049: { message: 'Ошибка выставления торгового поручения: %s', category: ApiErrorCategory.INVALID_ARGUMENT },
  30050: { message: 'Некорректный instrument_status.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30051: { message: 'Маржинальная торговля недоступна.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30052: { message: 'Инструмент запрещён для торгов через API.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30053: { message: 'Ошибка выставления стоп-заявки: %s', category: ApiErrorCategory.INVALID_ARGUMENT },
  30054: { message: 'Инструмент не является акцией или ETF.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30055: { message: 'order_id не может быть длиннее 36 символов.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30056: { message: 'Валюта стоп-заявки не поддерживается.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30057: { message: 'Заявка-дубль не найдена.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30058: { message: 'Задача ещё не завершена, попробуйте позже.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30059: { message: 'Ошибка отмены заявки: %s', category: ApiErrorCategory.INVALID_ARGUMENT },
  30060: { message: 'Ошибка отмены стоп-заявки: %s', category: ApiErrorCategory.INVALID_ARGUMENT },
  30061: { message: 'from вне допустимого диапазона.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30062: { message: 'to вне допустимого диапазона.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30063: { message: 'expire_date вне допустимого диапазона.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30064: { message: 'Период не может превышать 31 день.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30065: { message: 'Параметр task_id обязателен.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30066: { message: 'Параметр payload обязателен.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30067: { message: 'Некорректный action_type.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30068: { message: 'Доступны только лимитные заявки.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30069: { message: 'Параметр limit должен быть ≤ 1000.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30070: { message: 'from не может быть больше текущей даты.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30077: { message: 'Метод недоступен для внебиржевых инструментов.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30078: { message: 'Некорректный шаг цены.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30079: { message: 'Инструмент недоступен для торгов.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30080: { message: 'Количество лотов должно быть положительным.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30081: { message: 'Счёт закрыт.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30082: { message: 'Счёт заблокирован.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30083: { message: 'Некорректный тип заявки.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30084: { message: 'Превышен лимит запрашиваемого периода.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30085: { message: 'Цена в пунктах доступна только для фьючерсов и облигаций.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30086: { message: 'Некорректный год.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30087: { message: 'Параметр query обязателен.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30088: { message: 'from и to должны быть в одном году.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30089: { message: 'to не должно быть позднее %s.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30090: { message: 'Параметр siebel_id обязателен.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30091: { message: 'Количество инструментов не может превышать 100.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30092: { message: 'Торги недоступны по нерабочим дням.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30093: { message: 'figi или instrument_id обязателен.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30094: { message: 'Выставление заявок по опционам недоступно.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30095: { message: 'Заявка не исполнена биржей.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30096: { message: 'Заявка отклонена, попробуйте позже.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30097: { message: 'Несоответствующая торговая сессия.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30098: { message: 'Торги по инструменту сейчас не проводятся.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30099: { message: 'Цена вне лимитов по инструменту.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30100: { message: 'Цена должна быть положительной.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30101: { message: 'Для торговли инструментом пройдите тестирование.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30102: { message: 'Обязательные параметры указаны неправильно.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30103: { message: 'Доступна только заявка по лучшей цене.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30104: { message: 'Некорректный price_type.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30105: { message: 'Некорректный exchange_order_type.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30106: { message: 'Некорректный статус.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30107: { message: 'limit и page не могут быть отрицательными.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30108: { message: 'Количество брендов меньше запрашиваемых параметров.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30109: { message: 'Превышена максимальная сумма сделки.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30210: { message: 'Не заданы параметры trailing_data.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30211: { message: 'Не задан indent_type.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30212: { message: 'Не задан spread_type.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30213: { message: 'Некорректный indicator_type.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30214: { message: 'Некорректный type_of_price.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30215: { message: 'Некорректный length.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30216: { message: 'Некорректный deviation_data.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30217: { message: 'Некорректный smoothing_data.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30218: { message: 'Количество инструментов в списке не может превышать 3000.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30219: { message: 'Некорректный candle_source_type.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30220: { message: 'candle_type не поддерживается с limit.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30221: { message: 'order_request_id должен быть UUID.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30222: { message: 'signal_id должен быть UUID.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30223: { message: 'strategy_id должен быть UUID.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30224: { message: 'Некорректный strategy_type.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30225: { message: 'Некорректный параметр active.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30226: { message: 'Количество элементов меньше запрашиваемых параметров.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30227: { message: 'Заявка отменена.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30228: { message: 'Необходимо указать from или limit.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30229: { message: 'Конвертация цены фьючерса недоступна.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30230: { message: 'Параметр group_id обязателен.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30231: { message: 'group_name отсутствует или некорректен.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30232: { message: 'group_color отсутствует или некорректен.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30233: { message: 'Группа не может быть удалена.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30234: { message: 'Инструмент не поддерживается методом.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30235: { message: 'Для данного интервала свечи доступны данные за последние 30 дней.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30236: { message: 'Конвертация цены фьючерса недоступна.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30237: { message: 'Параметр instrument_id обязателен.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30238: { message: 'За указанный интервал операций нет.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30240: { message: 'Требуется подтверждение для непокрытой позиции.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30241: { message: 'take_profit_type не применим к данной стоп-заявке.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30242: { message: 'limit должен быть от 1 до 100.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30244: { message: 'Превышен максимальный интервал запроса.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30245: { message: 'Некорректный execution_status.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30246: { message: 'Некорректный параметр amount.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30247: { message: 'Параметр amount обязателен.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30248: { message: 'Параметр to_account_id обязателен.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30249: { message: 'Параметр from_account_id обязателен.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30250: { message: 'Некорректный to_account_id.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30251: { message: 'Ошибка выполнения транзакции.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30252: { message: 'Некорректный from_account_id.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30253: { message: 'Некорректная валюта.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30254: { message: 'Некорректный time_in_force.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30255: { message: 'Торговля по счёту запрещена.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30256: { message: 'Параметр transaction_id обязателен.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30257: { message: 'Некорректный transaction_id.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30258: { message: 'Указанная валюта недоступна для операции.', category: ApiErrorCategory.INVALID_ARGUMENT },
  30260: { message: 'Моментальное исполнение не поддерживается этим типом стоп-заявки.', category: ApiErrorCategory.INVALID_ARGUMENT },
  35001: { message: 'Достигнут лимит на открытие счетов в песочнице.', category: ApiErrorCategory.INVALID_ARGUMENT },
  40002: { message: 'Недостаточно прав для операции.', category: ApiErrorCategory.PERMISSION_DENIED },
  40003: { message: 'Токен доступа не найден или неактивен.', category: ApiErrorCategory.UNAUTHENTICATED },
  40004: { message: 'Выставление заявок недоступно с данного аккаунта.', category: ApiErrorCategory.PERMISSION_DENIED },
  40005: { message: 'Недостаточно прав для перевода средств.', category: ApiErrorCategory.PERMISSION_DENIED },
  50001: { message: 'Биржа не найдена.', category: ApiErrorCategory.NOT_FOUND },
  50002: { message: 'Инструмент не найден.', category: ApiErrorCategory.NOT_FOUND },
  50004: { message: 'Счёт не найден.', category: ApiErrorCategory.NOT_FOUND },
  50005: { message: 'Торговое поручение не найдено.', category: ApiErrorCategory.NOT_FOUND },
  50006: { message: 'Стоп-заявка не найдена.', category: ApiErrorCategory.NOT_FOUND },
  50007: { message: 'Задача не найдена.', category: ApiErrorCategory.NOT_FOUND },
  50008: { message: 'Источник данных по стаканам отсутствует.', category: ApiErrorCategory.NOT_FOUND },
  50009: { message: 'Актив не найден.', category: ApiErrorCategory.NOT_FOUND },
  50010: { message: 'Бренд не найден.', category: ApiErrorCategory.NOT_FOUND },
  50011: { message: 'Стратегия не найдена.', category: ApiErrorCategory.NOT_FOUND },
  50012: { message: 'Сигнал не найден.', category: ApiErrorCategory.NOT_FOUND },
  70001: { message: 'Внутренняя ошибка сервиса. Попробуйте позже.', category: ApiErrorCategory.INTERNAL },
  70002: { message: 'Неизвестная сетевая ошибка. Попробуйте позже.', category: ApiErrorCategory.INTERNAL },
  70003: { message: 'Внутренняя ошибка сервиса. Попробуйте позже.', category: ApiErrorCategory.INTERNAL },
  80001: { message: 'Превышен лимит одновременных стрим-соединений.', category: ApiErrorCategory.RESOURCE_EXHAUSTED },
  80002: { message: 'Превышен лимит запросов в минуту.', category: ApiErrorCategory.RESOURCE_EXHAUSTED },
  80003: { message: 'Превышен лимит отправки СМС.', category: ApiErrorCategory.RESOURCE_EXHAUSTED },
  80004: { message: 'В стриме отсутствуют активные подписки.', category: ApiErrorCategory.RESOURCE_EXHAUSTED },
  80005: { message: 'Превышено время жизни стрима.', category: ApiErrorCategory.RESOURCE_EXHAUSTED },
  80006: { message: 'Превышен лимит ошибок в минуту.', category: ApiErrorCategory.RESOURCE_EXHAUSTED },
  90001: { message: 'Требуется подтверждение операции: %s', category: ApiErrorCategory.FAILED_PRECONDITION },
  90002: { message: 'Инструмент доступен только квалифицированным инвесторам.', category: ApiErrorCategory.FAILED_PRECONDITION },
  90003: { message: 'Цена заявки слишком высокая.', category: ApiErrorCategory.FAILED_PRECONDITION },
};

export function handleApiError(error: any): ApiErrorResult {
  const grpcCode = error?.code;
  const details = error?.details || '';
  // Пытаемся извлечь бизнес-код T‑Invest из details (например, "80004")
  const match = details.match(/\b(\d{5})\b/);
  const businessCode = match ? parseInt(match[1], 10) : null;
  const code = businessCode || grpcCode; // приоритет бизнес-коду

  const info = errorMessages[code] || {
    message: `Неизвестная ошибка (код ${code}): ${details}`,
    category: ApiErrorCategory.INTERNAL,
  };

  const shouldRetry = info.category === ApiErrorCategory.INTERNAL || info.category === ApiErrorCategory.RESOURCE_EXHAUSTED;

  const win = getTradingAssistantWindow();
  if (win && !win.isDestroyed()) {
    win.webContents.send('api-error', {
      message: info.message,
      category: info.category,
      code,
      timestamp: Date.now(),
    });
  }

  return {
    message: info.message,
    category: info.category,
    shouldRetry,
    retryDelayMs: shouldRetry ? 1000 : undefined,
  };
}