// src/main/services/pranaBindu/mentat/thenicsCatalog.ts
//
// Каталог упражнений из приложения Thenics.
// Отдельно от PROGRESSIONS_CATALOG (Wade/Cali/Runner/Core/Posture/HIIT).
//
// Отличия от нашего каталога:
//   - 4 уровня сложности (Beginner / Intermediate / Advanced / Pro)
//     вместо 10 уровней Wade/Cali.
//   - Одно движение = одна запись (никаких levels[] с ladder).
//   - Есть weighted-варианты (Push Up +10Kg) и Ring/Band-упражнения —
//     в этом сэмпле не включены, добавим отдельно.
//
// Пока используется только как источник для таблицы equivalences
// (Melange v21). В matcher / генераторы не встроен.

export type ThenicsLevel = 'Beginner' | 'Intermediate' | 'Advanced' | 'Pro';

export interface ThenicsEntry {
  /** ID из исходной таблицы Thenics (1..265+). */
  id: number;
  /** Слаг-ключ: 'push-up', 'archer-pull-up'. Только lowercase, дефисы. */
  key: string;
  /** Название как в Thenics (англ.). */
  name: string;
  /** Русский перевод (если был в таблице). */
  nameRu?: string;
  level: ThenicsLevel;
  /** Группы мышц (Muscles + Muscles 2..6 из таблицы). */
  muscles?: string[];
  /** Оборудование (Equipment из таблицы). */
  equipment?: string[];
  youtube?: string;
}

export const THENICS_CATALOG: ThenicsEntry[] = [
  // ============ Push ============
  { id: 198, key: 'knee-push-up', name: 'Knee Push Up', level: 'Beginner',
    muscles: ['Arms', 'Chest'], equipment: ['No'] },
  { id: 4, key: 'push-up', name: 'Push Up', nameRu: 'Полные отжимания', level: 'Beginner',
    muscles: ['Arms', 'Chest'], equipment: ['No'] },
  { id: 116, key: 'diamond-push-up', name: 'Diamond Push Up', level: 'Beginner',
    muscles: ['Arms', 'Chest'], equipment: ['No'] },
  { id: 86, key: 'archer-push-up', name: 'Archer Push Up', level: 'Intermediate',
    muscles: ['Arms', 'Chest'], equipment: ['No'] },
  { id: 122, key: 'one-arm-push-up', name: 'One Arm Push Up', level: 'Advanced',
    muscles: ['Arms', 'Chest', 'Shoulders'], equipment: ['No'] },

  // ============ Pull (расширено) ============
  // --- Базовые подтягивания ---
  { id: 1, key: 'pull-up', name: 'Pull Up', nameRu: 'Полные подтягивания', level: 'Beginner',
    muscles: ['Arms', 'Back'], equipment: ['Bar'] },
  { id: 82, key: 'chin-up', name: 'Chin Up', level: 'Beginner',
    muscles: ['Arms', 'Back'], equipment: ['Bar'] },
  { id: 92, key: 'active-bar-hang', name: 'Active Bar Hang', level: 'Beginner',
    muscles: ['Arms', 'Back'], equipment: ['Bar'] },
  { id: 155, key: 'arch-active-hang', name: 'Arch Active Hang', level: 'Beginner',
    muscles: ['Arms', 'Back', 'Shoulders'], equipment: ['Bar'] },
  { id: 177, key: 'assisted-pull-up', name: 'Assisted Pull Up', level: 'Beginner',
    muscles: ['Arms', 'Back'], equipment: ['Bar and Resistance bend'] },
  { id: 178, key: 'negative-pull-up', name: 'Negative Pull Up', level: 'Beginner',
    muscles: ['Arms', 'Back'], equipment: ['Bar'] },
  { id: 175, key: 'towel-pull-up', name: 'Towel Pull Up', level: 'Beginner',
    muscles: ['Back'], equipment: ['Towel'] },

  // --- Тяги (horizontal pulls) ---
  { id: 2, key: 'body-row', name: 'Body Row', nameRu: 'Горизонтальные подтягивания', level: 'Beginner',
    muscles: ['Arms', 'Back'], equipment: ['Lower bar'] },
  { id: 186, key: 'body-row-45', name: 'Body Row 45°', level: 'Beginner',
    muscles: ['Arms', 'Back'], equipment: ['Lower bar'] },
  { id: 187, key: 'table-row', name: 'Table Row', level: 'Beginner',
    muscles: ['Arms', 'Back'], equipment: ['Table'] },
  { id: 185, key: 'towel-row', name: 'Towel Row', level: 'Beginner',
    muscles: ['Back'], equipment: ['Pillar, towel and resistance bend'] },
  { id: 188, key: 'advanced-body-row', name: 'Advanced Body Row', level: 'Intermediate',
    muscles: ['Arms', 'Back'], equipment: ['Lower bar and Elevation'] },
  { id: 189, key: 'archer-row', name: 'Archer Row', level: 'Intermediate',
    muscles: ['Arms', 'Back'], equipment: ['Lower bar'] },
  { id: 190, key: 'l-lever-row', name: 'L Lever Row', level: 'Intermediate',
    muscles: ['Arms', 'Back'], equipment: ['Lower bar'] },
  { id: 191, key: 'tuck-front-lever-row', name: 'Tuck Front Lever Row', level: 'Intermediate',
    muscles: ['Arms', 'Back'], equipment: ['Lower bar'] },
  { id: 192, key: 'adv-tuck-front-lever-row', name: 'Advanced Tuck Front Lever Row', level: 'Advanced',
    muscles: ['Arms', 'Back'], equipment: ['Lower bar'] },
  { id: 194, key: 'straddle-front-lever-row', name: 'Straddle Front Lever Row', level: 'Pro',
    muscles: ['Arms', 'Back'], equipment: ['Bar'] },
  { id: 196, key: 'front-lever-row', name: 'Front Lever Row', level: 'Pro',
    muscles: ['Arms', 'Back'], equipment: ['Lower bar'] },

  // --- Продвинутые подтягивания ---
  { id: 6, key: 'archer-pull-up', name: 'Archer Pull Up', nameRu: 'Подтягивания Лучник', level: 'Intermediate',
    muscles: ['Arms', 'Back'], equipment: ['Bar'] },
  { id: 8, key: 'pull-out', name: 'Pull Out', nameRu: 'Строгие латинские подтягивания', level: 'Intermediate',
    muscles: ['Arms', 'Back'], equipment: ['Bar'] },
  { id: 9, key: 'clapping-pull-up', name: 'Clapping Pull Up', nameRu: 'Подтягивания с хлопками', level: 'Intermediate',
    muscles: ['Arms', 'Back'], equipment: ['Bar'] },
  { id: 12, key: 'headbangers-pull-up', name: 'Headbangers Pull Up', nameRu: 'Подтягивания Головорезы', level: 'Intermediate',
    muscles: ['Arms', 'Back'], equipment: ['Bar'] },
  { id: 85, key: 'l-sit-chin-up', name: 'L-Sit Chin Up', level: 'Intermediate',
    muscles: ['Arms', 'Back'], equipment: ['Bar'] },
  { id: 93, key: 'typewriter-pull-up', name: 'Typewriter Pull Up', level: 'Intermediate',
    muscles: ['Arms', 'Back'], equipment: ['Bar'] },
  { id: 5, key: 'high-pull-up', name: 'High Pull Up', nameRu: 'Высокие подтягивания', level: 'Advanced',
    muscles: ['Arms', 'Back'], equipment: ['Bar'] },

  // --- Muscle Up ---
  { id: 10, key: 'negative-muscle-up', name: 'Negative Muscle Up', nameRu: 'Обратный выход силой', level: 'Intermediate',
    muscles: ['Arms', 'Chest', 'Back'], equipment: ['Bar'] },
  { id: 11, key: 'jumping-muscle-up', name: 'Jumping Muscle Up', nameRu: 'Прыжок с выходом силой', level: 'Intermediate',
    muscles: ['Arms', 'Back'], equipment: ['Lower bar'] },
  { id: 13, key: 'kipping-muscle-up', name: 'Kipping Muscle Up', nameRu: 'Грязный выход силой', level: 'Advanced',
    muscles: ['Arms', 'Chest', 'Back'], equipment: ['Bar'] },
  { id: 14, key: 'muscle-up', name: 'Muscle Up', nameRu: 'Выход силой', level: 'Advanced',
    muscles: ['Arms', 'Chest', 'Back'], equipment: ['Bar'] },

  // --- Одной рукой (прогрессия) ---
  { id: 94, key: 'one-arm-bar-hang', name: 'One Arm Bar Hang', level: 'Intermediate',
    muscles: ['Arms', 'Back'], equipment: ['Bar'] },
  { id: 95, key: 'assisted-one-arm-pull-up', name: 'Assisted One Arm Pull Up', level: 'Intermediate',
    muscles: ['Arms', 'Back'], equipment: ['Bar and Belt'] },
  { id: 96, key: 'one-arm-scapula-shrug', name: 'One Arm Scapula Shrug', level: 'Intermediate',
    muscles: ['Arms', 'Back'], equipment: ['Bar'] },
  { id: 97, key: 'one-arm-body-row', name: 'One Arm Body Row', level: 'Intermediate',
    muscles: ['Arms', 'Back'], equipment: ['Lower bar'] },
  { id: 98, key: 'negative-one-arm-pull-up', name: 'Negative One Arm Pull Up', level: 'Intermediate',
    muscles: ['Arms', 'Back'], equipment: ['Bar'] },
  { id: 99, key: 'little-assisted-one-arm-pull-up', name: 'Little Assisted One Arm Pull Up', level: 'Intermediate',
    muscles: ['Arms', 'Back'], equipment: ['Bar'] },
  { id: 100, key: 'one-arm-pull-up', name: 'One Arm Pull Up', level: 'Advanced',
    muscles: ['Arms', 'Back'], equipment: ['Bar'] },

  // --- Hefesto Pull ---
  { id: 145, key: 'assisted-hefesto-pull', name: 'Assisted Hefesto Pull', level: 'Beginner',
    muscles: ['Arms', 'Chest', 'Shoulders'], equipment: ['Lower bar'] },
  { id: 149, key: 'hefesto-pull', name: 'Hefesto Pull', level: 'Intermediate',
    muscles: ['Arms', 'Chest', 'Shoulders'], equipment: ['Bar'] },

  // ============ Push (расширено) ============
  { id: 114, key: 'incline-push-up', name: 'Incline Push Up', level: 'Beginner',
    muscles: ['Arms', 'Chest'], equipment: ['Bench or Chair'] },
  { id: 200, key: 'wide-push-up', name: 'Wide Push Up', level: 'Beginner',
    muscles: ['Arms', 'Chest'], equipment: ['No'] },
  { id: 15, key: 'pseudo-push-up', name: 'Pseudo Push Ups', nameRu: 'Псевдо отжимания', level: 'Beginner',
    muscles: ['Arms', 'Chest', 'Shoulders'], equipment: ['No'] },
  { id: 16, key: 'pseudo-planche-lean', name: 'Pseudo Planche Lean', nameRu: 'Псевдо планш отжимания', level: 'Beginner',
    muscles: ['Arms', 'Chest', 'Shoulders'], equipment: ['No'] },
  { id: 117, key: 'alligator-push-up', name: 'Alligator Push Up', level: 'Beginner',
    muscles: ['Arms', 'Chest', 'Shoulders'], equipment: ['No'] },
  { id: 56, key: 'pike-push-up', name: 'Pike Push Up', level: 'Beginner',
    muscles: ['Arms', 'Shoulders'], equipment: ['No'] },
  { id: 57, key: 'hindu-push-up', name: 'Hindu Push Up', level: 'Beginner',
    muscles: ['Arms', 'Shoulders'], equipment: ['No'] },
  { id: 119, key: 'incline-one-arm-push-up', name: 'Incline One Arm Push Up', level: 'Intermediate',
    muscles: ['Arms', 'Chest', 'Shoulders'], equipment: ['Bench or Chair'] },
  { id: 120, key: 'negative-one-arm-push-up', name: 'Negative One Arm Push Up', level: 'Intermediate',
    muscles: ['Arms', 'Chest', 'Shoulders'], equipment: ['No'] },
  { id: 201, key: 'plyo-push-up', name: 'Plyo Push Up', level: 'Intermediate',
    muscles: ['Arms', 'Chest'], equipment: ['No'] },
  { id: 203, key: 'back-clap-push-up', name: 'Back Clap Push Up', level: 'Intermediate',
    muscles: ['Arms', 'Chest'], equipment: ['No'] },
  { id: 218, key: 'tiger-bend-push-up', name: 'Tiger Bend Push Up', level: 'Intermediate',
    muscles: ['Arms'], equipment: ['No'] },
  { id: 121, key: 'rocky-push-up', name: 'Rocky Push Up', level: 'Advanced',
    muscles: ['Arms', 'Chest', 'Shoulders'], equipment: ['No'] },
  { id: 204, key: 'superman-push-up', name: 'Superman Push Up', level: 'Advanced',
    muscles: ['Arms', 'Chest'], equipment: ['No'] },

  // ============ Dip (расширено) ============
  { id: 216, key: 'bench-dip', name: 'Bench Dip', level: 'Beginner',
    muscles: ['Arms'], equipment: ['Bench'] },
  { id: 217, key: 'advanced-bench-dip', name: 'Advanced Bench Dip', level: 'Beginner',
    muscles: ['Arms'], equipment: ['Bench and Elevation'] },
  { id: 3, key: 'dip', name: 'Dip', nameRu: 'Отжимания на брусьях', level: 'Beginner',
    muscles: ['Arms', 'Chest'], equipment: ['Push up bars'] },
  { id: 7, key: 'straight-bar-dip', name: 'Straight Bar Dip', nameRu: 'Прямые отжимания на брусьях', level: 'Beginner',
    muscles: ['Arms', 'Chest'], equipment: ['Bar'] },
  { id: 66, key: 'scapula-dip', name: 'Scapula Dip', level: 'Beginner',
    muscles: ['Arms'], equipment: ['No'] },
  { id: 70, key: 'advanced-scapula-dip', name: 'Advanced Scapula Dips', level: 'Beginner',
    muscles: ['Arms'], equipment: ['Bench [Parallettes]'] },
  { id: 83, key: 'elbow-dip', name: 'Elbow Dip', level: 'Intermediate',
    muscles: ['Arms'], equipment: ['Push up bars'] },
  { id: 144, key: 'korean-dip', name: 'Korean Dip', level: 'Intermediate',
    muscles: ['Arms', 'Chest', 'Shoulders'], equipment: ['Lower bar'] },
  { id: 219, key: 'russian-dip', name: 'Russian Dip', level: 'Intermediate',
    muscles: ['Arms', 'Chest'], equipment: ['Push up bars'] },
  { id: 225, key: 'archer-dip', name: 'Archer Dip', level: 'Intermediate',
    muscles: ['Arms', 'Chest'], equipment: ['Lower bar'] },
  { id: 227, key: 'clap-dip', name: 'Clap Dip', level: 'Intermediate',
    muscles: ['Arms', 'Chest'], equipment: ['Push up bars'] },
  { id: 146, key: 'hefesto-dip', name: 'Hefesto Dip', level: 'Intermediate',
    muscles: ['Arms', 'Chest', 'Shoulders'], equipment: ['Lower bar'] },
  { id: 148, key: 'negative-hefesto', name: 'Negative Hefesto', level: 'Intermediate',
    muscles: ['Arms', 'Chest', 'Shoulders'], equipment: ['Lower bar'] },
  { id: 228, key: '180-dip', name: '180 Dip', level: 'Advanced',
    muscles: ['Arms', 'Chest'], equipment: ['Push up bars'] },
  { id: 151, key: 'assisted-hefesto', name: 'Assisted Hefesto', level: 'Advanced',
    muscles: ['Arms', 'Chest', 'Shoulders'], equipment: ['Bar and Resistance band'] },
  { id: 229, key: 'impossible-dip', name: 'Impossible Dip', level: 'Pro',
    muscles: ['Arms', 'Chest'], equipment: ['Push up bars'] },
  { id: 152, key: 'hefesto', name: 'Hefesto', level: 'Pro',
    muscles: ['Arms', 'Chest', 'Shoulders'], equipment: ['Bar'] },

  // ============ Squat (расширено) ============
  { id: 231, key: 'chair-squat', name: 'Chair Squat', level: 'Beginner',
    muscles: ['Legs'], equipment: ['Bench or Chair'] },
  { id: 232, key: 'squat', name: 'Squat', level: 'Beginner',
    muscles: ['Legs'], equipment: ['No'] },
  { id: 48, key: 'deep-squat-hold', name: 'Deep Squat Hold', level: 'Beginner',
    muscles: ['Legs'], equipment: ['No'] },
  { id: 45, key: 'deep-squat', name: 'Deep Squat', level: 'Beginner',
    muscles: ['Legs'], equipment: ['No'] },
  { id: 46, key: 'lunge', name: 'Lunge', level: 'Beginner',
    muscles: ['Legs'], equipment: ['No'] },
  { id: 137, key: 'reverse-lunge', name: 'Reverse Lunge', level: 'Beginner',
    muscles: ['Legs'], equipment: ['No'] },
  { id: 138, key: 'narrow-split-squat', name: 'Narrow Split Squat', level: 'Beginner',
    muscles: ['Legs'], equipment: ['No'] },
  { id: 139, key: 'split-squat', name: 'Split Squat', level: 'Beginner',
    muscles: ['Legs'], equipment: ['No'] },
  { id: 140, key: 'supported-shrimp-squat', name: 'Supported Shrimp Squat', level: 'Beginner',
    muscles: ['Legs'], equipment: ['No'] },
  { id: 47, key: 'one-leg-calf-raise', name: 'One Leg Calf Raise', level: 'Beginner',
    muscles: ['Legs'], equipment: ['Treshold'] },
  { id: 89, key: 'calf-raise', name: 'Calf Raise', level: 'Beginner',
    muscles: ['Legs'], equipment: ['Elevation'] },
  { id: 49, key: 'bulgarian-squat', name: 'Bulgarian Squat', level: 'Intermediate',
    muscles: ['Legs'], equipment: ['Bench or Chair'] },
  { id: 50, key: 'archer-squat', name: 'Archer Squat', level: 'Intermediate',
    muscles: ['Legs'], equipment: ['No'] },
  { id: 51, key: 'bench-pistol-squat', name: 'Bench Pistol Squat', level: 'Intermediate',
    muscles: ['Legs'], equipment: ['Bench or Chair'] },
  { id: 84, key: 'jumping-squat', name: 'Jumping Squat', level: 'Intermediate',
    muscles: ['Legs'], equipment: ['No'] },
  { id: 90, key: 'jumping-lunge', name: 'Jumping Lunge', level: 'Intermediate',
    muscles: ['Legs'], equipment: ['No'] },
  { id: 233, key: 'curtsy-squat', name: 'Curtsy Squat', level: 'Intermediate',
    muscles: ['Legs'], equipment: ['No'] },
  { id: 235, key: 'jump-squat-tuck', name: 'Jump Squat with Tuck', level: 'Intermediate',
    muscles: ['Legs'], equipment: ['No'] },
  { id: 87, key: 'glute-bridge', name: 'Glute Bridge', level: 'Beginner',
    muscles: ['Legs'], equipment: ['No'] },
  { id: 91, key: 'one-leg-glute-bridge', name: 'One Leg Glute Bridge', level: 'Intermediate',
    muscles: ['Legs'], equipment: ['No'] },
  { id: 88, key: 'wall-sit', name: 'Wall Sit', level: 'Beginner',
    muscles: ['Legs'], equipment: ['Wall'] },
  { id: 141, key: 'no-arm-shrimp-squat', name: 'No Arm Shrimp Squat', level: 'Intermediate',
    muscles: ['Legs'], equipment: ['No'] },
  { id: 142, key: 'one-arm-shrimp-squat', name: 'One Arm Shrimp Squat', level: 'Intermediate',
    muscles: ['Legs'], equipment: ['No'] },
  { id: 52, key: 'assisted-pistol-squat', name: 'Assisted Pistol Squat', level: 'Advanced',
    muscles: ['Legs'], equipment: ['Pillar'] },
  { id: 53, key: 'rolling-pistol-squat', name: 'Rolling Pistol Squat', level: 'Advanced',
    muscles: ['Legs'], equipment: ['No'] },
  { id: 54, key: 'elevated-pistol-squat', name: 'Elevated Pistol Squat', level: 'Advanced',
    muscles: ['Legs'], equipment: ['Treshold'] },
  { id: 55, key: 'pistol-squat', name: 'Pistol Squat', level: 'Advanced',
    muscles: ['Legs'], equipment: ['No'] },
  { id: 143, key: 'shrimp-squat', name: 'Shrimp Squat', level: 'Advanced',
    muscles: ['Legs'], equipment: ['No'] },

  // ============ Leg Raise / Core (расширено) ============
  { id: 65, key: 'straddle-leg-raise-hold', name: 'Straddle Leg Raise Hold', level: 'Beginner',
    muscles: ['Abs'], equipment: ['No'] },
  { id: 67, key: 'straddle-leg-raises', name: 'Straddle Leg Raises', level: 'Beginner',
    muscles: ['Abs'], equipment: ['No'] },
  { id: 68, key: 'knee-raises', name: 'Knee Raises', level: 'Beginner',
    muscles: ['Abs'], equipment: ['Bar'] },
  { id: 69, key: 'leg-raise-hold', name: 'Leg Raise Hold', level: 'Beginner',
    muscles: ['Abs'], equipment: ['No'] },
  { id: 73, key: 'advanced-leg-raises', name: 'Advanced Leg Raises', level: 'Beginner',
    muscles: ['Abs'], equipment: ['No'] },
  { id: 118, key: 'one-arm-plank', name: 'One Arm Plank', level: 'Beginner',
    muscles: ['Abs'], equipment: ['No'] },
  { id: 102, key: 'side-plank', name: 'Side Plank', level: 'Beginner',
    muscles: ['Abs'], equipment: ['No'] },
  { id: 249, key: 'side-plank-raise', name: 'Side Plank Raise', level: 'Beginner',
    muscles: ['Abs'], equipment: ['No'] },
  { id: 248, key: 'knee-side-raise', name: 'Knee Side Raise', level: 'Beginner',
    muscles: ['Abs'], equipment: ['No'] },
  { id: 243, key: 'russian-twist', name: 'Russian Twist', level: 'Beginner',
    muscles: ['Abs'], equipment: ['No'] },
  { id: 244, key: 'bicycle', name: 'Bicycle', level: 'Beginner',
    muscles: ['Abs'], equipment: ['No'] },
  { id: 247, key: 'climber', name: 'Climber', level: 'Beginner',
    muscles: ['Arms', 'Chest', 'Abs'], equipment: ['No'] },
  { id: 253, key: 'cross-climber', name: 'Cross Climber', level: 'Beginner',
    muscles: ['Abs'], equipment: ['No'] },
  { id: 128, key: 'hollow-arch-roll', name: 'Hollow Arch Roll', level: 'Beginner',
    muscles: ['Abs'], equipment: ['No'] },
  { id: 250, key: 'lying-tuck-hold', name: 'Lying Tuck Hold', level: 'Beginner',
    muscles: ['Abs'], equipment: ['No'] },
  { id: 251, key: 'tuck-reverse-crunch', name: 'Tuck Reverse Crunch', level: 'Beginner',
    muscles: ['Abs'], equipment: ['No'] },
  { id: 262, key: 'cobra-pose', name: 'Cobra Pose', level: 'Beginner',
    muscles: ['Abs'], equipment: ['No'] },
  { id: 29, key: 'toes-to-bar', name: 'Toes to Bar', level: 'Intermediate',
    muscles: ['Abs'], equipment: ['Bar'] },
  { id: 245, key: 'bar-leg-raises', name: 'Bar Leg Raises', level: 'Intermediate',
    muscles: ['Abs'], equipment: ['Bar'] },
  { id: 252, key: 'reverse-crunch', name: 'Reverse Crunch', level: 'Intermediate',
    muscles: ['Abs'], equipment: ['No'] },
  { id: 254, key: 'plank-walk', name: 'Plank Walk', level: 'Intermediate',
    muscles: ['Abs'], equipment: ['No'] },
  { id: 256, key: 'advanced-plank-walk', name: 'Advanced Plank Walk', level: 'Intermediate',
    muscles: ['Abs'], equipment: ['No'] },
  { id: 255, key: 'hollow-body-rocks', name: 'Hollow Body Rocks', level: 'Intermediate',
    muscles: ['Abs'], equipment: ['No'] },
  { id: 246, key: 'jackknife', name: 'Jackknife', level: 'Advanced',
    muscles: ['Abs'], equipment: ['No'] },
  { id: 257, key: 'tuck-dragon-flag', name: 'Tuck Dragon Flag', level: 'Intermediate',
    muscles: ['Abs'], equipment: ['Bench or Pillar'] },
  { id: 258, key: 'half-dragon-flag', name: 'Half Dragon Flag', level: 'Intermediate',
    muscles: ['Abs'], equipment: ['Bench or Pillar'] },
  { id: 259, key: 'one-leg-dragon-flag', name: 'One Leg Dragon Flag', level: 'Intermediate',
    muscles: ['Abs'], equipment: ['Bench or Pillar'] },
  { id: 260, key: 'straddle-dragon-flag', name: 'Straddle Dragon Flag', level: 'Advanced',
    muscles: ['Abs'], equipment: ['Bench or Pillar'] },
  { id: 261, key: 'negative-dragon-flag', name: 'Negative Dragon Flag', level: 'Advanced',
    muscles: ['Abs'], equipment: ['Bench or Pillar'] },

  // ============ Leg Raise / Core ============
  { id: 17, key: 'leg-raise', name: 'Leg Raise', nameRu: 'Подъём ног', level: 'Beginner',
    muscles: ['Abs'], equipment: ['No'] },
  { id: 115, key: 'plank', name: 'Plank', level: 'Beginner',
    muscles: ['Abs'], equipment: ['No'] },
  { id: 127, key: 'hollow-body-hold', name: 'Hollow Body Hold', level: 'Beginner',
    muscles: ['Abs'], equipment: ['No'] },
  { id: 34, key: 'dragon-flag', name: 'Dragon Flag', level: 'Advanced',
    muscles: ['Abs'], equipment: ['Bench, Pillar or Very low bar'] },

  // ============ Handstand ============
  { id: 58, key: 'headstand', name: 'Headstand', level: 'Beginner',
    muscles: ['Arms', 'Shoulders'], equipment: ['No'] },
  { id: 59, key: 'wall-handstand', name: 'Wall Handstand', level: 'Beginner',
    muscles: ['Arms', 'Shoulders'], equipment: ['Wall'] },
  { id: 123, key: 'downward-dog', name: 'Downward Dog', level: 'Beginner',
    muscles: ['Shoulders'], equipment: ['No'] },
  { id: 124, key: 'pike-hold', name: 'Pike Hold', level: 'Beginner',
    muscles: ['Shoulders'], equipment: ['Lower elevation or Higher elevation'] },
  { id: 125, key: 'advanced-wall-handstand', name: 'Advanced Wall Handstand', level: 'Beginner',
    muscles: ['Shoulders'], equipment: ['Wall'] },
  { id: 213, key: 'pike-walk', name: 'Pike Walk', level: 'Beginner',
    muscles: ['Shoulders'], equipment: ['No'] },
  { id: 214, key: 'tuck-to-handstand', name: 'Tuck to Handstand', level: 'Beginner',
    muscles: ['Arms', 'Chest', 'Shoulders'], equipment: ['Parallettes'] },
  { id: 60, key: 'advanced-pike-push-up', name: 'Advanced Pike Push Up', level: 'Intermediate',
    muscles: ['Arms', 'Shoulders'], equipment: ['Bench or Chair'] },
  { id: 62, key: 'handstand', name: 'Handstand', level: 'Intermediate',
    muscles: ['Arms', 'Shoulders'], equipment: ['No'] },
  { id: 126, key: 'diamond-handstand', name: 'Diamond Handstand', level: 'Intermediate',
    muscles: ['Shoulders'], equipment: ['No'] },
  { id: 129, key: 'wall-walks', name: 'Wall Walks', level: 'Intermediate',
    muscles: ['Arms', 'Shoulders', 'Abs'], equipment: ['Wall'] },
  { id: 130, key: 'wall-bend-straddle-handstand', name: 'Wall Bend Straddle Handstand', level: 'Intermediate',
    muscles: ['Arms', 'Shoulders', 'Abs'], equipment: ['Wall'] },
  { id: 131, key: 'bend-straddle-handstand', name: 'Bend Straddle Handstand', level: 'Intermediate',
    muscles: ['Arms', 'Shoulders', 'Abs'], equipment: ['No'] },
  { id: 133, key: 'wall-fingertip-straddle-handstand', name: 'Wall Fingertip Straddle Handstand', level: 'Intermediate',
    muscles: ['Arms', 'Shoulders', 'Abs'], equipment: ['Wall'] },
  { id: 61, key: 'wall-handstand-push-up', name: 'Wall Handstand Push Up', level: 'Advanced',
    muscles: ['Arms', 'Shoulders'], equipment: ['Wall'] },
  { id: 63, key: 'negative-handstand-push-up', name: 'Negative Handstand Push Up', level: 'Advanced',
    muscles: ['Arms', 'Shoulders'], equipment: ['No, Parallettes or Push up bars'] },
  { id: 64, key: 'handstand-push-up', name: 'Handstand Push Up', level: 'Advanced',
    muscles: ['Arms', 'Shoulders'], equipment: ['No, Parallettes or Push up bars'] },
  { id: 132, key: 'fingertip-straddle-handstand', name: 'Fingertip Straddle Handstand', level: 'Advanced',
    muscles: ['Arms', 'Shoulders', 'Abs'], equipment: ['No'] },
  { id: 134, key: 'straddle-one-arm-handstand', name: 'Straddle One Arm Handstand', level: 'Advanced',
    muscles: ['Arms', 'Shoulders', 'Abs'], equipment: ['No'] },
  { id: 135, key: 'diamond-one-arm-handstand', name: 'Diamond One Arm Handstand', level: 'Advanced',
    muscles: ['Arms', 'Shoulders', 'Abs'], equipment: ['No'] },
  { id: 215, key: 'deep-handstand-push-up', name: 'Deep Handstand Push Up', level: 'Advanced',
    muscles: ['Arms', 'Chest', 'Shoulders'], equipment: ['Push up bars'] },
  { id: 136, key: 'one-arm-handstand', name: 'One Arm Handstand', level: 'Pro',
    muscles: ['Arms', 'Shoulders', 'Abs'], equipment: ['No'] },
  { id: 230, key: 'tiger-bend-handstand-push-up', name: 'Tiger Bend Handstand Push Up', level: 'Pro',
    muscles: ['Arms', 'Chest', 'Shoulders'], equipment: ['No'] },

  // ============ Planche ============
  { id: 19, key: 'frog-stand', name: 'Frog Stand', level: 'Beginner',
    muscles: ['Arms', 'Chest', 'Shoulders'], equipment: ['No'] },
  { id: 22, key: 'tuck-planche-swing', name: 'Tuck Planche Swing', level: 'Beginner',
    muscles: ['Chest', 'Shoulders', 'Abs'], equipment: ['No'] },
  { id: 20, key: 'tuck-planche', name: 'Tuck Planche', level: 'Intermediate',
    muscles: ['Chest', 'Shoulders', 'Abs'], equipment: ['No'] },
  { id: 24, key: 'handstand-lean', name: 'Handstand Lean', level: 'Intermediate',
    muscles: ['Arms', 'Shoulders'], equipment: ['No [Chairs, Parallettes or Push up bars]'] },
  { id: 205, key: 'tuck-planche-push-up', name: 'Tuck Planche Push Up', level: 'Intermediate',
    muscles: ['Arms', 'Chest', 'Shoulders'], equipment: ['Parallettes or Push up bars'] },
  { id: 21, key: 'advanced-tuck-planche', name: 'Advanced Tuck Planche', level: 'Advanced',
    muscles: ['Arms', 'Shoulders', 'Abs'], equipment: ['No'] },
  { id: 23, key: 'straddle-planche', name: 'Straddle Planche', level: 'Advanced',
    muscles: ['Arms', 'Shoulders', 'Abs'], equipment: ['No [Parallettes or Push up bars]'] },
  { id: 208, key: 'advanced-tuck-planche-push-up', name: 'Advanced Tuck Planche Push Up', level: 'Advanced',
    muscles: ['Arms', 'Chest', 'Shoulders'], equipment: ['Push up bars'] },
  { id: 209, key: 'straddle-planche-push-up', name: 'Straddle Planche Push Up', level: 'Advanced',
    muscles: ['Arms', 'Chest', 'Shoulders'], equipment: ['No'] },
  { id: 25, key: 'planche', name: 'Planche', level: 'Pro',
    muscles: ['Arms', 'Shoulders', 'Abs'], equipment: ['No [Parallettes or Push up bars]'] },
  { id: 211, key: 'planche-push-up', name: 'Planche Push Up', level: 'Pro',
    muscles: ['Arms', 'Chest', 'Shoulders'], equipment: ['Parallettes'] },

  // ============ Lever (только Front Lever — Back Lever в Заходе 5) ============
  { id: 35, key: 'front-lever', name: 'Front Lever', level: 'Advanced',
    muscles: ['Arms', 'Back', 'Abs'], equipment: ['Bar'] },
];

/** Поиск по слагу. */
export function findThenicsByKey(key: string): ThenicsEntry | undefined {
  return THENICS_CATALOG.find((e) => e.key === key);
}

/** Поиск по имени (регистронезависимо, без дефисов). */
export function findThenicsByName(name: string): ThenicsEntry | undefined {
  const norm = name.trim().toLowerCase().replace(/-/g, ' ');
  return THENICS_CATALOG.find(
    (e) => e.name.toLowerCase().replace(/-/g, ' ') === norm
  );
}